//! Repo Wiki generation (M8).
//!
//! Produces a module / architecture overview of the workspace by reusing the
//! M5 codebase index (`{project}/.agentz/index.db`). The generation is
//! deterministic and dependency-light — it aggregates the indexed chunks by
//! top-level module and language and highlights the largest files — so it works
//! offline without an LLM. The result is written to `{project}/.agentz/REPO_WIKI.md`
//! and returned to the caller for preview.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use rusqlite::Connection;

use crate::commands::codebase::{build_index, CodeSearchHit};
use crate::commands::data_scope::require_project_dir;

fn index_db_path(root: &Path) -> PathBuf {
    root.join(".agentz").join("index.db")
}

/// Per-module aggregate stats accumulated from the index.
#[derive(Default)]
struct ModuleStat {
    files: std::collections::HashSet<String>,
    chunks: usize,
    /// language (extension) -> chunk count
    langs: BTreeMap<String, usize>,
}

fn top_module(path: &str) -> String {
    match path.split_once('/') {
        Some((head, _)) => head.to_string(),
        None => "(root)".to_string(),
    }
}

fn ext_of(path: &str) -> String {
    path.rsplit_once('.')
        .map(|(_, e)| e.to_lowercase())
        .filter(|e| e.len() <= 8)
        .unwrap_or_else(|| "—".to_string())
}

/// Build the wiki markdown for `root`, (re)building the index if it is empty.
pub fn generate(root: &Path) -> Result<String, String> {
    // Ensure the index exists / is populated.
    let conn = Connection::open(index_db_path(root)).map_err(|e| format!("open index db: {e}"))?;
    let has_chunks: i64 = conn
        .query_row("SELECT COUNT(*) FROM chunks", [], |r| r.get(0))
        .unwrap_or(0);
    drop(conn);
    if has_chunks == 0 {
        build_index(root)?;
    }

    let conn = Connection::open(index_db_path(root)).map_err(|e| format!("open index db: {e}"))?;

    // Per-file chunk counts (proxy for size / importance).
    let mut stmt = conn
        .prepare("SELECT path, COUNT(*) FROM chunks GROUP BY path")
        .map_err(|e| format!("prepare: {e}"))?;
    let rows = stmt
        .query_map([], |r| Ok((r.get::<_, String>(0)?, r.get::<_, i64>(1)?)))
        .map_err(|e| format!("query: {e}"))?;

    let mut modules: BTreeMap<String, ModuleStat> = BTreeMap::new();
    let mut file_chunks: Vec<(String, i64)> = Vec::new();
    let mut total_files = 0usize;
    let mut total_chunks = 0usize;
    for row in rows.flatten() {
        let (path, chunks) = row;
        total_files += 1;
        total_chunks += chunks as usize;
        file_chunks.push((path.clone(), chunks));
        let m = modules.entry(top_module(&path)).or_default();
        m.files.insert(path.clone());
        m.chunks += chunks as usize;
        *m.langs.entry(ext_of(&path)).or_default() += chunks as usize;
    }

    if total_files == 0 {
        return Err("index is empty — nothing to document".to_string());
    }

    // Overall language breakdown.
    let mut lang_totals: BTreeMap<String, usize> = BTreeMap::new();
    for m in modules.values() {
        for (lang, c) in &m.langs {
            *lang_totals.entry(lang.clone()).or_default() += c;
        }
    }
    let mut lang_sorted: Vec<(String, usize)> = lang_totals.into_iter().collect();
    lang_sorted.sort_by_key(|x| std::cmp::Reverse(x.1));

    // Largest files overall.
    file_chunks.sort_by_key(|x| std::cmp::Reverse(x.1));

    // Modules sorted by chunk weight.
    let mut module_sorted: Vec<(&String, &ModuleStat)> = modules.iter().collect();
    module_sorted.sort_by_key(|x| std::cmp::Reverse(x.1.chunks));

    let project_name = root
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "workspace".to_string());
    let now = chrono::Utc::now().format("%Y-%m-%d %H:%M UTC").to_string();

    let mut md = String::new();
    md.push_str(&format!("# {project_name} — Repo Wiki\n\n"));
    md.push_str(&format!(
        "_Auto-generated by AgentZ from the codebase index on {now}._\n\n"
    ));
    md.push_str(&format!(
        "**{total_files}** indexed files · **{total_chunks}** code chunks · \
         **{}** top-level modules.\n\n",
        module_sorted.len()
    ));

    md.push_str("## Languages\n\n");
    for (lang, c) in lang_sorted.iter().take(12) {
        let pct = (*c as f64 / total_chunks.max(1) as f64) * 100.0;
        md.push_str(&format!("- `.{lang}` — {c} chunks ({pct:.0}%)\n"));
    }
    md.push('\n');

    md.push_str("## Modules\n\n");
    md.push_str("Top-level directories, ordered by code weight:\n\n");
    for (name, stat) in module_sorted.iter().take(40) {
        let mut langs: Vec<(&String, &usize)> = stat.langs.iter().collect();
        langs.sort_by(|a, b| b.1.cmp(a.1));
        let lang_str = langs
            .iter()
            .take(3)
            .map(|(l, _)| format!(".{l}"))
            .collect::<Vec<_>>()
            .join(", ");
        md.push_str(&format!(
            "### `{name}/`\n- {} files · {} chunks · {}\n\n",
            stat.files.len(),
            stat.chunks,
            if lang_str.is_empty() {
                "—".into()
            } else {
                lang_str
            }
        ));
    }

    md.push_str("## Largest files\n\n");
    md.push_str("Likely entry points / hotspots (by indexed size):\n\n");
    for (path, chunks) in file_chunks.iter().take(25) {
        md.push_str(&format!("- `{path}` — {chunks} chunks\n"));
    }
    md.push('\n');

    md.push_str("---\n\n");
    md.push_str(
        "> Tip: ask the Agent to expand any module here, or use `@codebase` in chat \
         to pull relevant code into a conversation.\n",
    );

    Ok(md)
}

/// Optionally surface a few representative search hits (unused helper kept for
/// callers that want richer wiki sections later).
#[allow(dead_code)]
pub fn sample_hits(root: &Path, query: &str) -> Vec<CodeSearchHit> {
    crate::commands::codebase::search_index(root, query, 5).unwrap_or_default()
}

// ─── Tauri command ────────────────────────────────────────────────────────

/// Generate the Repo Wiki, write it to `.agentz/REPO_WIKI.md`, and return the
/// markdown plus the relative path it was written to.
#[tauri::command]
pub async fn repo_wiki_generate(project_dir: Option<String>) -> Result<RepoWikiResult, String> {
    let project = require_project_dir(project_dir.as_deref())?;
    let root = PathBuf::from(project);
    tokio::task::spawn_blocking(move || {
        let md = generate(&root)?;
        let out_dir = root.join(".agentz");
        std::fs::create_dir_all(&out_dir).map_err(|e| format!("create .agentz: {e}"))?;
        let out = out_dir.join("REPO_WIKI.md");
        std::fs::write(&out, &md).map_err(|e| format!("write wiki: {e}"))?;
        Ok(RepoWikiResult {
            path: ".agentz/REPO_WIKI.md".to_string(),
            markdown: md,
        })
    })
    .await
    .map_err(|e| format!("wiki task failed: {e}"))?
}

#[derive(Debug, serde::Serialize)]
pub struct RepoWikiResult {
    pub path: String,
    pub markdown: String,
}
